import type { Metadata } from "next";
import Link from "next/link";
import "../globals.css";
import { getAllPages } from "../../../sanity/sanity-utils";

export const metadata: Metadata = {
  title: "Jagdish Pal | Projects",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getAllPages();
  return (
    <html lang="en">
      <body
        className={"max-w-3xl mx-auto py-10"}
      >
        <header className="flex items-center justify-between">
          <Link href={"/"} className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-900 bg-clip-text text-transparent text-lg font-bold">Home
          </Link>
          <div className="flex items-center gap-3">
          {pages.map(page=>(
            <Link key={page._id} href={`/${page.slug}`} className="text-right ml-4 text-gray-600 hover:text-gray-800">
              {page.title}
            </Link>
          ))}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
